name: powerbank_web_checkout
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.8
  web: ^1.1.1
  # localization
  easy_localization: ^3.0.8

  # state management
  flutter_bloc: ^9.1.1

  # value equality
  equatable: ^2.0.7

  # service locator
  get_it: ^8.0.3

  # internet
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1

  # deep links
  app_links: ^6.4.0

  # navigation
  auto_route: ^10.1.0+1

  # code generator from models (to json and from json)
  json_serializable: ^6.9.5

  # API manager
  retrofit: ^4.6.0
  provider: ^6.1.5
  in_app_purchase: ^3.2.3
  flutter_svg: ^2.2.0

dev_dependencies:
  # route generator
  auto_route_generator: ^10.1.0

  # code generator
  build_runner: ^2.5.4

  retrofit_generator: ^9.6.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    # localization
    - assets/resources/langs/
    #  assets
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
